name: Lint GitHub Actions workflows

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: rhysd/actionlint@8571752353ac232ba0f7698fc1df248b61a3690d
